export const CHANGE_USERNAME = '/Home/CHANGE_USERNAME';
export const GET_API_DATA_BASE = '/HOME/GET_API_DATA_BASE';
export const GET_DATA_SUCCESS = '/HOME/GET_API_DATA_SUCCESS';
export const GET_DATA_ERROR = '/HOME/GET_API_DATA_ERROR';
